In [ ]:
import pandas as pd

In [ ]:
marks = pd.Series([85, 90, 78, 92])

print(marks)

0    85
1    90
2    78
3    92
dtype: int64

In [ ]:
marks = pd.Series(
    [85, 90, 78],
    index=["Aman", "Rahul", "Priya"]
)

print(marks)
print(marks["Rahul"])  # 90

Aman     85
Rahul    90
Priya    78
dtype: int64
90

In [ ]:
df = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Priya", "Neha"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 90, 78, 92],
    "City": ["Patna", "Delhi", "Patna", "Mumbai"]
})

print(df)
print(df.head())
print(df.tail(2))
print(df.shape)
df.info()	#Column names, data types and non-null counts
df.describe()	#Statistical summary of numerical columns

    Name  Age  Marks    City
0   Aman   20     85   Patna
1  Rahul   21     90   Delhi
2  Priya   20     78   Patna
3   Neha   22     92  Mumbai
    Name  Age  Marks    City
0   Aman   20     85   Patna
1  Rahul   21     90   Delhi
2  Priya   20     78   Patna
3   Neha   22     92  Mumbai
    Name  Age  Marks    City
2  Priya   20     78   Patna
3   Neha   22     92  Mumbai
(4, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
 3   City    4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

             Age      Marks
count   4.000000   4.000000
mean   20.750000  86.250000
std     0.957427   6.238322
min    20.000000  78.000000
25%    20.000000  83.250000
50%    20.500000  87.500000
75%    21.250000  90.500000
max    22.000000  92.000000

In [ ]:
df.columns	#All column names
df.dtypes	#Data type of each column

Name     object
Age       int64
Marks     int64
City     object
dtype: object

In [ ]:
df.index	#Row index labels
df.shape	#Number of rows and columns
df.size	#Total number of cells

16

In [ ]:
print(df["Name"])
print(df["Marks"])

0     Aman
1    Rahul
2    Priya
3     Neha
Name: Name, dtype: object
0    85
1    90
2    78
3    92
Name: Marks, dtype: int64

In [ ]:
print(df[["Name", "Marks"]])

    Name  Marks
0   Aman     85
1  Rahul     90
2  Priya     78
3   Neha     92

In [ ]:
#iloc selects by integer position, starting from zero.
print(df.iloc[0])
print(df.iloc[0:2])
print(df.iloc[1, 2])
#loc selects by index label.
print(df.loc[0])

Name      Aman
Age         20
Marks       85
City     Patna
Name: 0, dtype: object
    Name  Age  Marks   City
0   Aman   20     85  Patna
1  Rahul   21     90  Delhi
90
Name      Aman
Age         20
Marks       85
City     Patna
Name: 0, dtype: object

In [ ]:
df2 = df.set_index("Name")

print(df2.loc["Rahul"])

Age         21
Marks       90
City     Delhi
Name: Rahul, dtype: object

In [ ]:
print(df[df["Marks"] > 80])

    Name  Age  Marks    City
0   Aman   20     85   Patna
1  Rahul   21     90   Delhi
3   Neha   22     92  Mumbai

In [ ]:
result = df[
    (df["Marks"] > 80) &
    (df["Age"] > 20)
]

print(result)

    Name  Age  Marks    City
1  Rahul   21     90   Delhi
3   Neha   22     92  Mumbai

In [ ]:
result = df[~(df["Marks"] > 80)]

In [ ]:
print(df.sort_values("Marks"))

    Name  Age  Marks    City
2  Priya   20     78   Patna
0   Aman   20     85   Patna
1  Rahul   21     90   Delhi
3   Neha   22     92  Mumbai

In [ ]:
print(
    df.sort_values(
        ["City", "Marks"],
        ascending=[True, False]
    )
)
#This sorts by city alphabetically, then sorts marks from highest to lowest within each city.

    Name  Age  Marks    City
1  Rahul   21     90   Delhi
3   Neha   22     92  Mumbai
0   Aman   20     85   Patna
2  Priya   20     78   Patna

In [ ]:
print(df["Marks"].mean())    # Average
print(df["Marks"].median())  # Median
print(df["Marks"].max())     # Maximum
print(df["Marks"].min())     # Minimum
print(df["Marks"].sum())     # Sum
print(df["Marks"].std())     # Standard deviation
print(df["Marks"].value_counts())

86.25
87.5
92
78
345
6.238322424070967
Marks
85    1
90    1
78    1
92    1
Name: count, dtype: int64

In [ ]:
idx = df["Marks"].idxmax()

print(df.loc[idx])
#idxmax() returns the index label of the maximum value, so loc retrieves the corresponding row.

Name       Neha
Age          22
Marks        92
City     Mumbai
Name: 3, dtype: object

handling missing cases

In [ ]:
df = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Priya", "Neha"],
    "Age": [20, None, 20, 22],
    "Marks": [85, 90, None, 92]
})

print(df)

    Name   Age  Marks
0   Aman  20.0   85.0
1  Rahul   NaN   90.0
2  Priya  20.0    NaN
3   Neha  22.0   92.0

In [ ]:
print(df.isnull())

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [ ]:
print(df.isnull().sum())
#count missing value per column

Name     0
Age      1
Marks    1
dtype: int64

In [ ]:
print(df.isnull().sum().sum())

2

In [ ]:
df_clean = df.dropna()
#This removes rows containing at least one missing value by default.
#It does not change the original df unless you assign the result back or use an appropriate in-place operation.

In [ ]:
print(df)

    Name   Age  Marks
0   Aman  20.0   85.0
1  Rahul   NaN   90.0
2  Priya  20.0    NaN
3   Neha  22.0   92.0

Fill the missing value either by mean ,mode,median

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Marks"] = df["Marks"].fillna(df["Marks"].median())

In [ ]:
print(df)

    Name        Age  Marks
0   Aman  20.000000   85.0
1  Rahul  20.666667   90.0
2  Priya  20.000000   90.0
3   Neha  22.000000   92.0

In [ ]:
df = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Priya"],
    "Marks": [85, 90, 78]
})

df["Passed"] = df["Marks"] >= 40

df["Bonus_Marks"] = df["Marks"] + 5

print(df)

    Name  Marks  Passed  Bonus_Marks
0   Aman     85    True           90
1  Rahul     90    True           95
2  Priya     78    True           83

In [ ]:
df = df.rename(columns={"Marks": "Score"})

In [ ]:
print(df)

    Name  Score  Passed  Bonus_Marks
0   Aman     85    True           90
1  Rahul     90    True           95
2  Priya     78    True           83

In [ ]:
df["Score"] = df["Score"].astype(float)
df = df.drop(columns=["Bonus_Marks"])

In [ ]:
print(df)

    Name  Score  Passed
0   Aman   85.0    True
1  Rahul   90.0    True
2  Priya   78.0    True

In [ ]:
#for readnig a csv file
#df = pd.read_csv("students.csv")

1. Load data
pd.read_csv()

2. Inspect data
head(), info(), describe()

3. Clean data
isnull(), fillna(), dropna()

4. Explore data
filtering, statistics, groupby()

5. Select features
X = df[feature_columns]

6. Select target
y = df[target_column]

7. Split data
Train/test split using scikit-learn

8. Train model
Fit a model and evaluate it